language: node_js

cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - '12'

git:
  depth: 3

script:
  - yarn build

notifications:
  email:
    recipients:
    - wdb.team.web@gmail.com
    - briangerardo114@gmail.com
    on_success: always
    on_failier: always

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-brach: gh-pages
  commit_message: "Deploy del proyecto"
  on:
    branch: master


